### ISSUE TITLE
NPE from ServletUtil when no cookies exist. 

### ISSUE THREAD

**Issue by SteveHarney** [BorderTech/wcomponents#1682]
When using a container that correctly follows the javaEE  specification

com.github.bordertech.wcomponents.servlet.ServletUtil.extractCookie

throws a Null Pointer Exception when no cookie are sent on the request.  as the request.getCookies can return null as per https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletRequest.html#getCookies--

This does not occur in Jetty 8 returns an object regardless of if cookies were provided on the request or not. 

java.lang.NullPointerException
        at com.github.bordertech.wcomponents.servlet.ServletUtil.extractCookie(ServletUtil.java:658)
        at com.github.bordertech.wcomponents.container.TransformXMLInterceptor.preparePaint(TransformXMLInterceptor.java:103)
        at com.github.bordertech.wcomponents.container.InterceptorComponent.preparePaint(InterceptorComponent.java:177)
        at com.github.bordertech.wcomponents.container.AbstractContainerHelper.render(AbstractContainerHelper.java:241)
        at com.github.bordertech.wcomponents.servlet.ServletUtil.processRequest(ServletUtil.java:194)
        at com.github.bordertech.wcomponents.servlet.WServlet.serviceInt(WServlet.java:147)
        at com.github.bordertech.wcomponents.servlet.WServlet.service(WServlet.java:110)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

**Comment by ricksbrown** [comment]
@SteveHarney Thanks mate, much obliged for reporting this and the link to HttpServletRequest. 

IMHO poor API design, I'm in the "[Empty collection. Always](https://stackoverflow.com/questions/1969993/is-it-better-to-return-null-or-empty-collection)." camp, but yeah, we'll have to deal with this regardless.

**Comment by ricksbrown** [comment]
Released in 1.5.18
