### ISSUE TITLE
WTree as AJAX trigger breaks expansion

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#447]
With WTree:

1. make the tree a trigger for a WAjaxControl; **and** 
2. `setExpandMode` as either `LAZY` or `DYNAMIC`; **then**
3. expand any exapndable treeitem.

## Expected

The tree item's content is loaded and displayed.

## Actual

The application throws an error. Stack trace below. It appears that the "special case" for expansion is interfering with regular WAjaxControl processing.

```
SEVERE: Error processing AJAX request in action phase. GET is not supported for the AJAX trigger eg-tree.
java.lang.IllegalStateException: GET is not supported for the AJAX trigger eg-tree.
	at com.github.bordertech.wcomponents.container.AjaxInterceptor.serviceRequest(AjaxInterceptor.java:79)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.SubordinateControlInterceptor.serviceRequest(SubordinateControlInterceptor.java:37)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.ContextCleanupInterceptor.serviceRequest(ContextCleanupInterceptor.java:36)
	at com.github.bordertech.wcomponents.container.WrongStepAjaxInterceptor.serviceRequest(WrongStepAjaxInterceptor.java:80)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.WWindowInterceptor.serviceRequest(WWindowInterceptor.java:60)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.AjaxSetupInterceptor.serviceRequest(AjaxSetupInterceptor.java:60)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.SessionTokenAjaxInterceptor.serviceRequest(SessionTokenAjaxInterceptor.java:55)
	at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
	at com.github.bordertech.wcomponents.container.AjaxErrorInterceptor.serviceRequest(AjaxErrorInterceptor.java:32)
	at com.github.bordertech.wcomponents.container.AbstractContainerHelper.processAction(AbstractContainerHelper.java:179)
	at com.github.bordertech.wcomponents.servlet.ServletUtil.processRequest(ServletUtil.java:171)
	at com.github.bordertech.wcomponents.servlet.WServlet.serviceInt(WServlet.java:142)
	at com.github.bordertech.wcomponents.servlet.WServlet.service(WServlet.java:105)
	at com.github.bordertech.wcomponents.lde.TestServlet.service(TestServlet.java:376)
	at com.github.bordertech.wcomponents.lde.PlainLauncher.service(PlainLauncher.java:115)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at com.github.bordertech.wcomponents.lde.TestServlet.service(TestServlet.java:167)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jonathanaustin** [comment]
WTree and WMultiFileWidget have the same AJAX problem....They are the only two components that are AjaxTriggers but also have "internal" AJAX for their own functionality.

Have to rethink how we "register" AJAX or handle the "internal" ajax actions.....

What do you think of something like this....

As WTree and WMultiFileWidget need to be a trigger and also their own "internal" ajax trigger, would it be hard from the client that for AJAX requests that are for the component itself (which also applies to WPanel, WCollapsible, WTable..etc) that the request parameter is "wc_ajax_self" instead of "wc_ajax". And when an AjaxTrigger is actually being an external trigger the request parameter is "wc_ajax".

WDYT @marksreeves @ricksbrown

**Comment by ricksbrown** [comment]
Could we assume "internal" Ajax requests will be "get" and external Ajax triggers will be "post". If this is correct would that not be enough to distinguish between them?

**Comment by jonathanaustin** [comment]
It would be nice to assume "internal" AJAX is "get", but there are some exceptions. eg WTable uses "put" for its internal AJAX.

But....might be enough for the moment to get WTree and WMultiFileWidget working.

**Comment by marksreeves** [comment]
WTable has to report the state of all of its internal and descendant components. It has to be a POST (not a PUT - @jonathanaustin are you sure you are getting a PUT? I checked the JS and it _should_ be POSTing). It is an outlier compared to other "internal" AJAX which acquires content for a given container so is OK to be a GET.

I don't think we can change tables to use GET. When changing page (for example) we would lose the state of expanded/selected rows and any user input into editable descendants if we only GET the next page. This is so far from optimal it is the sort of thing we used to do.

We can, however, assume GET is internal for WTree if that is any help?

**Comment by jonathanaustin** [comment]
@marksreeves My bad...meant POST.

Agree. WTable definitely needs to be a POST. For example, if the cells are editable, even though an AJAX pagination action is "internal", it needs to POST the editable ROW information.

But...If we can assume WTree and WMultiFileWidget use GET for their internal AJAX we will be OK. As they are the only components which are also an AjaxTrigger. So for these components, when it is an internal action it is "GET" and when they are triggering an Ajax Action it will be a "POST".

I will also implement a new marker interface AjaxInternalTrigger. Any components that require AJAX for their internal state can implement this marker interface and they no longer have to "register" their own AJAX operation as the AJAX intercepters will create the Ajax Operation when the ajax request is received for this component (either POST or GET). This means we can remove all the "preparePaint" methods that use to call AjaxHelper.registerComponentTargetItself(getId(), request).
