### ISSUE TITLE
WMenu Type.COLUMN WSubMenu Ajax failure

### ISSUE THREAD

**Issue by marksreeves** [BorderTech/wcomponents#889]
Given a WMenu Type.COLUMN with a WSubMenu with SubmenuMode.DYNAMIC:

1. Open the submenu and select an item in that submenu which causes a trip to the server
2. repeat.

Expect: the submenu is populated using an AJAX call when it is opened in step 2
Actual: an error message appears where the submenu content applies

```
SEVERE: Error processing AJAX request in action phase. No AJAX operation has been registered for trigger eg_0c1a0a1c.
com.github.bordertech.wcomponents.util.SystemException: No AJAX operation has been registered for trigger eg_0c1a0a1c.
  at com.github.bordertech.wcomponents.container.AjaxSetupInterceptor.serviceRequest(AjaxSetupInterceptor.java:67)
  at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
  at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
  at com.github.bordertech.wcomponents.container.SessionTokenAjaxInterceptor.serviceRequest(SessionTokenAjaxInterceptor.java:54)
  at com.github.bordertech.wcomponents.container.InterceptorComponent.serviceRequest(InterceptorComponent.java:165)
  at com.github.bordertech.wcomponents.container.AjaxErrorInterceptor.serviceRequest(AjaxErrorInterceptor.java:32)
  at com.github.bordertech.wcomponents.container.AbstractContainerHelper.processAction(AbstractContainerHelper.java:164)
  at com.github.bordertech.wcomponents.servlet.ServletUtil.processRequest(ServletUtil.java:186)
  at com.github.bordertech.wcomponents.servlet.WServlet.serviceInt(WServlet.java:142)
  at com.github.bordertech.wcomponents.servlet.WServlet.service(WServlet.java:105)
  at com.github.bordertech.wcomponents.lde.TestServlet.service(TestServlet.java:346)
  at com.github.bordertech.wcomponents.lde.PlainLauncher.service(PlainLauncher.java:114)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
  at com.github.bordertech.wcomponents.lde.TestServlet.service(TestServlet.java:134)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
  at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
  at org.eclipse.jetty.server.Server.handle(Server.java:370)
  at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
  at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
  at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
  at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
  at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
  at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
  at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
  at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by marksreeves** [comment]
It appears that any DYNAMIC or LAZY WSubMenu will cause this. See the
