### ISSUE TITLE
ComponentModel writeExternal does not support private fields

### ISSUE THREAD

**Issue by Joshua-Barclay** [BorderTech/wcomponents#914]
Serializing `ComponentModel` can have issues due to the `writeExternal` method.

```java
public class ComponentModel implements WebModel, Externalizable 

       @Override
       public void writeExternal(final ObjectOutput out) throws IOException {
              Field[] fields = getFields(this);

              for (Field field : fields) {
                     try {
                           if (sharedModel == null) {
                                  // Support serialization of the static model,
                                  // even though this should not occur.
                                  Object value = field.get(this);
                                  out.writeObject(value);
                           } else if (unsetFields != null && unsetFields.contains(field)) {
                                  // Support the unlikely case being deserialized/serialized
                                  // in short succession without the shared model being set.
                                  out.writeObject(NoOverride.INSTANCE);
                           } else {
                                  Object sharedValue = field.get(sharedModel);
                                  Object value = field.get(this);
...
```

The field.get throws java.lang.IllegalArgumentException: Possible if it is accessing a private field.  Should we be calling `field.setAccessible(true)` first?

The exception is:
```java
java.lang.IllegalArgumentException: Can not set au.gov.immi.elp.ui.formshell.FormShell field au.gov.immi.elp.ui.formshell.FormShellContainer$FormShellContainerModel.formShell to com.github.bordertech.wcomponents.WPanel$PanelModel
       at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:176)
       at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:180)
       at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:67)
       at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:48)
       at java.lang.reflect.Field.get(Field.java:391)
```

**Comment by kandula-aswin** [comment]
Added a Unit test and executed using Java 8, but couldn't reproduce the exception
kandula-aswin/wcomponents@5e97ea0

Is the test correct?

**Comment by marksreeves** [comment]
@jonathanaustin could you please take a look at the test @kandula-aswin created?

**Comment by kandula-aswin** [comment]
Currently `writeExternal` excludes ComponentModel's static and [transient fields](https://github.com/BorderTech/wcomponents/blob/georgie/wcomponents-core/src/main/java/com/github/bordertech/wcomponents/ComponentModel.java#L782). So `unsetFields` field is excluded from serialisation.

But when [transient fields](https://github.com/kandula-aswin/wcomponents/blob/georgie/wcomponents-core/src/main/java/com/github/bordertech/wcomponents/ComponentModel.java#L782) are included, this test fails with a different error:
```
java.io.NotSerializableException: java.lang.reflect.Field
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.github.bordertech.wcomponents.ComponentModel.writeExternal(ComponentModel.java:747)
	at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1459)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1430)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.github.bordertech.wcomponents.ComponentModel.writeExternal(ComponentModel.java:759)
	at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1459)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1430)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.github.bordertech.wcomponents.ComponentModel_Test.testWriteExternal(ComponentModel_Test.java:69)
```
